# Generated by Django 6.0.6 on 2026-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Public URL of the venue image.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='sports',
            field=models.JSONField(blank=True, default=list, help_text="List of sports available at this venue, e.g. ['Badminton', 'Squash']."),
        ),
    ]
