# Generated by Django 6.0.6 on 2026-06-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_image_url_and_sports_to_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in INR charged per one-hour slot.', max_digits=8),
        ),
    ]
